apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: streaming-pipeline-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: REDIS_HOST
              value: redis
